#!/bin/sh

# Decrypt keys
yadm decrypt

# Initialize ssh agent
eval "$(ssh-agent -s)"

# add ssh key to agent
ssh-add ~/.ssh/id_ed25519

# Import gpg keys
gpg --import "$HOME/.gnupg/.exported-keyring"/*.asc
gpg --import-ownertrust "$HOME/.gnupg/.exported-keyring"/ownertrust.txt

# Change remote of repo and fetch new one
yadm remote remove origin
yadm remote add origin git@gitlab.com:lamp216/dotfiles.git
yadm fetch origin
yadm push --set-upstream origin master
