#? Config file for btop v. 1.4.7
color_theme = "/home/perfectime94/.config/btop/themes/catppuccin_mocha.theme"
theme_background = True
truecolor = True
vim_keys = True
rounded_corners = True
proc_gradient = True
proc_tree = True
show_battery = True
temp_scale = "celsius"
update_ms = 1500
