# Fondo Dracula, a juego con Alacritty y ashell (#bd93f9 es tu primary_color).
preload = /home/perfectime94/Imágenes/fondos/second-collection/soft-waves/dracula-soft-waves-bd93f9.png
wallpaper = eDP-1,/home/perfectime94/Imágenes/fondos/second-collection/soft-waves/dracula-soft-waves-bd93f9.png
wallpaper = DP-2,/home/perfectime94/Imágenes/fondos/second-collection/soft-waves/dracula-soft-waves-bd93f9.png
splash = false
ipc = on
