import = [
   "~/.config/alacritty/dracula.toml"
]

live_config_reload = true

[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.bold]
family = "Iosevka Term"
style = "Bold"

[font.italic]
family = "Iosevka Term"
style = "Italic"

[font.normal]
family = "Iosevka Term"
style = "Regular"

[window]
dynamic_padding = true
opacity = 0.8
decorations_theme_variant = "Dark"
